# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_grad_posterior_density <- function(THETAi, Yi, MUi, invS, TAU, LAMBDA, J, K) {
    .Call(`_credicpp_cpp_grad_posterior_density`, THETAi, Yi, MUi, invS, TAU, LAMBDA, J, K)
}

cpp_posterior_density <- function(THETAi, Yi, MUi, invS, TAU, LAMBDA, J, K) {
    .Call(`_credicpp_cpp_posterior_density`, THETAi, Yi, MUi, invS, TAU, LAMBDA, J, K)
}

